[package]
name = "ar_particles"
version = "0.1.0"
edition = "2021"

[dependencies]

bevy_hanabi = { workspace = true }
bevy = { workspace = true }

[lints]
workspace = true


[dependencies.ar_core]
path = "../ar_core"

[dependencies.ar_battle]
path = "../ar_battle"