[package]
name = "ar_oneshot"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }

[lints]
workspace = true



[dependencies.ar_core]
path = "../ar_core"

[dependencies.ar_level]
path = "../ar_level"