[package]
name = "ar_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_xpbd_2d = { workspace = true }
bevy_asset_loader = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
